version: '3.7'

services:
  core:
    build:
      context: ./services/core
      dockerfile: Dockerfile.prod
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    expose:
      - 5000
    env_file:
      - ./.env.prod
  nginx:
    build: ./services/nginx
    ports:
      - 8081:80
    depends_on:
      - core
